<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\Sura;

class SuraSeeder extends Seeder
{
    public function run(): void
    {
        $suras = [
            ['id' => 1, 'name' => 'الفاتحة', 'ayas_count' => 7],
            ['id' => 2, 'name' => 'البقرة', 'ayas_count' => 286],
            ['id' => 3, 'name' => 'آل عمران', 'ayas_count' => 200],
            ['id' => 4, 'name' => 'النساء', 'ayas_count' => 176],
            ['id' => 5, 'name' => 'المائدة', 'ayas_count' => 120],
            ['id' => 6, 'name' => 'الأنعام', 'ayas_count' => 165],
            ['id' => 7, 'name' => 'الأعراف', 'ayas_count' => 206],
            ['id' => 8, 'name' => 'الأنفال', 'ayas_count' => 75],
            ['id' => 9, 'name' => 'التوبة', 'ayas_count' => 129],
            ['id' => 10, 'name' => 'يونس', 'ayas_count' => 109],
            ['id' => 11, 'name' => 'هود', 'ayas_count' => 123],
            ['id' => 12, 'name' => 'يوسف', 'ayas_count' => 111],
            ['id' => 13, 'name' => 'الرعد', 'ayas_count' => 43],
            ['id' => 14, 'name' => 'إبراهيم', 'ayas_count' => 52],
            ['id' => 15, 'name' => 'الحجر', 'ayas_count' => 99],
            ['id' => 16, 'name' => 'النحل', 'ayas_count' => 128],
            ['id' => 17, 'name' => 'الإسراء', 'ayas_count' => 111],
            ['id' => 18, 'name' => 'الكهف', 'ayas_count' => 110],
            ['id' => 19, 'name' => 'مريم', 'ayas_count' => 98],
            ['id' => 20, 'name' => 'طه', 'ayas_count' => 135],
            ['id' => 21, 'name' => 'الأنبياء', 'ayas_count' => 112],
            ['id' => 22, 'name' => 'الحج', 'ayas_count' => 78],
            ['id' => 23, 'name' => 'المؤمنون', 'ayas_count' => 118],
            ['id' => 24, 'name' => 'النور', 'ayas_count' => 64],
            ['id' => 25, 'name' => 'الفرقان', 'ayas_count' => 77],
            ['id' => 26, 'name' => 'الشعراء', 'ayas_count' => 227],
            ['id' => 27, 'name' => 'النمل', 'ayas_count' => 93],
            ['id' => 28, 'name' => 'القصص', 'ayas_count' => 88],
            ['id' => 29, 'name' => 'العنكبوت', 'ayas_count' => 69],
            ['id' => 30, 'name' => 'الروم', 'ayas_count' => 60],
            ['id' => 31, 'name' => 'لقمان', 'ayas_count' => 34],
            ['id' => 32, 'name' => 'السجدة', 'ayas_count' => 30],
            ['id' => 33, 'name' => 'الأحزاب', 'ayas_count' => 73],
            ['id' => 34, 'name' => 'سبأ', 'ayas_count' => 54],
            ['id' => 35, 'name' => 'فاطر', 'ayas_count' => 45],
            ['id' => 36, 'name' => 'يس', 'ayas_count' => 83],
            ['id' => 37, 'name' => 'الصافات', 'ayas_count' => 182],
            ['id' => 38, 'name' => 'ص', 'ayas_count' => 88],
            ['id' => 39, 'name' => 'الزمر', 'ayas_count' => 75],
            ['id' => 40, 'name' => 'غافر', 'ayas_count' => 85],
            ['id' => 41, 'name' => 'فصلت', 'ayas_count' => 54],
            ['id' => 42, 'name' => 'الشورى', 'ayas_count' => 53],
            ['id' => 43, 'name' => 'الزخرف', 'ayas_count' => 89],
            ['id' => 44, 'name' => 'الدخان', 'ayas_count' => 59],
            ['id' => 45, 'name' => 'الجاثية', 'ayas_count' => 37],
            ['id' => 46, 'name' => 'الأحقاف', 'ayas_count' => 35],
            ['id' => 47, 'name' => 'محمد', 'ayas_count' => 38],
            ['id' => 48, 'name' => 'الفتح', 'ayas_count' => 29],
            ['id' => 49, 'name' => 'الحجرات', 'ayas_count' => 18],
            ['id' => 50, 'name' => 'ق', 'ayas_count' => 45],
            ['id' => 51, 'name' => 'الذاريات', 'ayas_count' => 60],
            ['id' => 52, 'name' => 'الطور', 'ayas_count' => 49],
            ['id' => 53, 'name' => 'النجم', 'ayas_count' => 62],
            ['id' => 54, 'name' => 'القمر', 'ayas_count' => 55],
            ['id' => 55, 'name' => 'الرحمن', 'ayas_count' => 78],
            ['id' => 56, 'name' => 'الواقعة', 'ayas_count' => 96],
            ['id' => 57, 'name' => 'الحديد', 'ayas_count' => 29],
            ['id' => 58, 'name' => 'المجادلة', 'ayas_count' => 22],
            ['id' => 59, 'name' => 'الحشر', 'ayas_count' => 24],
            ['id' => 60, 'name' => 'الممتحنة', 'ayas_count' => 13],
            ['id' => 61, 'name' => 'الصف', 'ayas_count' => 14],
            ['id' => 62, 'name' => 'الجمعة', 'ayas_count' => 11],
            ['id' => 63, 'name' => 'المنافقون', 'ayas_count' => 11],
            ['id' => 64, 'name' => 'التغابن', 'ayas_count' => 18],
            ['id' => 65, 'name' => 'الطلاق', 'ayas_count' => 12],
            ['id' => 66, 'name' => 'التحريم', 'ayas_count' => 12],
            ['id' => 67, 'name' => 'الملك', 'ayas_count' => 30],
            ['id' => 68, 'name' => 'القلم', 'ayas_count' => 52],
            ['id' => 69, 'name' => 'الحاقة', 'ayas_count' => 52],
            ['id' => 70, 'name' => 'المعارج', 'ayas_count' => 44],
            ['id' => 71, 'name' => 'نوح', 'ayas_count' => 28],
            ['id' => 72, 'name' => 'الجن', 'ayas_count' => 28],
            ['id' => 73, 'name' => 'المزمل', 'ayas_count' => 20],
            ['id' => 74, 'name' => 'المدثر', 'ayas_count' => 56],
            ['id' => 75, 'name' => 'القيامة', 'ayas_count' => 40],
            ['id' => 76, 'name' => 'الإنسان', 'ayas_count' => 31],
            ['id' => 77, 'name' => 'المرسلات', 'ayas_count' => 50],
            ['id' => 78, 'name' => 'النبأ', 'ayas_count' => 40],
            ['id' => 79, 'name' => 'النازعات', 'ayas_count' => 46],
            ['id' => 80, 'name' => 'عبس', 'ayas_count' => 42],
            ['id' => 81, 'name' => 'التكوير', 'ayas_count' => 29],
            ['id' => 82, 'name' => 'الانفطار', 'ayas_count' => 19],
            ['id' => 83, 'name' => 'المطففين', 'ayas_count' => 36],
            ['id' => 84, 'name' => 'الانشقاق', 'ayas_count' => 25],
            ['id' => 85, 'name' => 'البروج', 'ayas_count' => 22],
            ['id' => 86, 'name' => 'الطارق', 'ayas_count' => 17],
            ['id' => 87, 'name' => 'الأعلى', 'ayas_count' => 19],
            ['id' => 88, 'name' => 'الغاشية', 'ayas_count' => 26],
            ['id' => 89, 'name' => 'الفجر', 'ayas_count' => 30],
            ['id' => 90, 'name' => 'البلد', 'ayas_count' => 20],
            ['id' => 91, 'name' => 'الشمس', 'ayas_count' => 15],
            ['id' => 92, 'name' => 'الليل', 'ayas_count' => 21],
            ['id' => 93, 'name' => 'الضحى', 'ayas_count' => 11],
            ['id' => 94, 'name' => 'الشرح', 'ayas_count' => 8],
            ['id' => 95, 'name' => 'التين', 'ayas_count' => 8],
            ['id' => 96, 'name' => 'العلق', 'ayas_count' => 19],
            ['id' => 97, 'name' => 'القدر', 'ayas_count' => 5],
            ['id' => 98, 'name' => 'البينة', 'ayas_count' => 8],
            ['id' => 99, 'name' => 'الزلزلة', 'ayas_count' => 8],
            ['id' => 100, 'name' => 'العاديات', 'ayas_count' => 11],
            ['id' => 101, 'name' => 'القارعة', 'ayas_count' => 11],
            ['id' => 102, 'name' => 'التكاثر', 'ayas_count' => 8],
            ['id' => 103, 'name' => 'العصر', 'ayas_count' => 3],
            ['id' => 104, 'name' => 'الهمزة', 'ayas_count' => 9],
            ['id' => 105, 'name' => 'الفيل', 'ayas_count' => 5],
            ['id' => 106, 'name' => 'قريش', 'ayas_count' => 4],
            ['id' => 107, 'name' => 'الماعون', 'ayas_count' => 7],
            ['id' => 108, 'name' => 'الكوثر', 'ayas_count' => 3],
            ['id' => 109, 'name' => 'الكافرون', 'ayas_count' => 6],
            ['id' => 110, 'name' => 'النصر', 'ayas_count' => 3],
            ['id' => 111, 'name' => 'المسد', 'ayas_count' => 5],
            ['id' => 112, 'name' => 'الإخلاص', 'ayas_count' => 4],
            ['id' => 113, 'name' => 'الفلق', 'ayas_count' => 5],
            ['id' => 114, 'name' => 'الناس', 'ayas_count' => 6],
        ];

        foreach ($suras as $sura) {
            Sura::updateOrCreate(['id' => $sura['id']], $sura);
        }
    }
}
